---
- name: Simple starter playbook
  hosts: all
  become: true

  tasks:
  - name: Add basics packages that must be installed on all decent system
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - ncat
      - lsof
      - iproute
      - git
      - curl
